apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/install.yaml
  - neco/service.yaml
patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/cybozu/argocd
    newTag: 1.7.7.4
  - name: quay.io/cybozu/dex
    newTag: 2.22.0.2
  - name: quay.io/cybozu/redis
    newTag: 5.0.8.3
