apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../template
  - httpproxy.yaml
  - objectbucketclaim.yaml
  - service.yaml
patchesStrategicMerge:
  - deployment.yaml
patches:
  - target:
      kind: Deployment
      name: registry
    patch: |-
      - op: replace
        path: /metadata/name
        value: quay-registry
