apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- maneki-apps.yaml
patchesStrategicMerge:
- argocd-ingress.yaml
- argocd.yaml
- bmc-reverse-proxy.yaml
- cert-manager.yaml
- coil.yaml
- external-dns.yaml
- metallb.yaml
- monitoring.yaml
- registry-elastic.yaml
- registry-ghcr.yaml
- registry-quay.yaml
- rook.yaml
- secrets.yaml
- teleport.yaml
