apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teleport-proxy-tls
  namespace: teleport
spec:
  secretName: teleport-proxy-tls
  issuerRef:
    kind: ClusterIssuer
    name: clouddns
  commonName: "*.teleport.osaka0.cybozu-ne.co"
  dnsNames:
    - teleport.osaka0.cybozu-ne.co
    - "*.teleport.osaka0.cybozu-ne.co"
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
