apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: clouddns
spec:
  acme:
    externalAccountBinding:
      keyID: wwxKZVO5df00sc1950lnjQ
      keySecretRef:
        name: zero-ssl-eabsecret-20201221
        key: eab-hmac-key
      keyAlgorithm: HS256
    email: neco@cybozu.com
    privateKeySecretRef:
      name: zerossl-secret
    server: https://acme.zerossl.com/v2/DV90
    solvers:
      - dns01:
          clouddns:
            project: cybozu-neco
            serviceAccountSecretRef:
              key: account.json
              name: clouddns
        selector:
          dnsZones:
            - stage0.cybozu-ne.co
