apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-quay
  namespace: argocd
spec:
  source:
    helm:
      parameters:
        - name: "httpproxy.fqdn"
          value: quay.registry.tokyo0.cybozu-ne.co
        - name: "proxy.secretName"
          value: quay-credential-t5c62bctdb
