apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |-
    version: 0.1
    log:
      level: info
    storage:
      s3:
        region: "neco"
        secure: false
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
      debug:
        addr: :5001
        prometheus:
          enabled: true
          path: /metrics
    compatibility:
      schema1:
        enabled: true
